import Sidebar from "./dashboard/components/Sidebar";
import Topbar from "./dashboard/components/Topbar";

import { Geist, Geist_Mono, Urbanist, Poppins } from "next/font/google";
import "../globals.css";
import UserProvider from "@/app/UserContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  fallback: ["sans-serif"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  fallback: ["sans-serif"],
});
export const metadata = {
  title: "MechaLink",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${urbanist.variable} ${poppins.variable} antialiased`}
      >
        <UserProvider>
          <div className="flex h-screen">
            {/* Sidebar: sticky to left */}
            <Sidebar className="sticky top-0" />

            {/* Main content */}
            <div className="flex-1 flex flex-col overflow-hidden">
              {/* Topbar: sticky to top */}
              <Topbar className="sticky top-0 z-10 shadow-sm" />

              {/* Scrollable content */}
              <div className="flex-1 overflow-auto p-4 bg-gray-50">
                <main>{children}</main>
              </div>
            </div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
