// app/layout.js
import { Geist, Geist_Mono, Urbanist, Poppins } from "next/font/google";
import "../globals.css";
// import UserProvider from "../UserContext";
import Header from "../Components/Header";
import Footer from "../Components/Footer";
import NextAuthProvider from "@/Providers/NextAuthProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  fallback: ["sans-serif"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  fallback: ["sans-serif"],
});
export const metadata = {
  title: "MechaLink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${urbanist.variable} ${poppins.variable} antialiased`}
      >
        <NextAuthProvider>
          {/* <UserProvider> */}
          <div className="flex flex-col min-h-screen justify-between pt-18">
            <Header />
            {children}
            <Footer />
          </div>
          {/* </UserProvider> */}
        </NextAuthProvider>
      </body>
    </html>
  );
}
